### ISSUE TITLE
Build failed on Mac

### ISSUE THREAD

**Issue by UCLGuichard** [ome/homebrew-alt#139]
Dear all,
I face a build failed while trying to install OMERO on my MacBook Pro. 
The message is:

==> ./build.py -Dice.home=/usr/local/opt/ice build-all
Last 15 lines from /Users/rolandguichard/Library/Logs/Homebrew/omero53/01.build.py:
		:: com.zeroc#icegrid;${versions.ice}: not found
		:: com.zeroc#freeze;${versions.ice}: not found
		:: zeroc#ice-db;${versions.ice}: not found
		::::::::::::::::::::::::::::::::::::::::::::::

:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS

BUILD FAILED
/private/tmp/omero53-20170905-69872-1sh6pqq/openmicroscopy-5.3.3/build.xml:157: The following error occurred while executing this line:
/private/tmp/omero53-20170905-69872-1sh6pqq/openmicroscopy-5.3.3/components/antlib/resources/global.xml:426: The following error occurred while executing this line:
/private/tmp/omero53-20170905-69872-1sh6pqq/openmicroscopy-5.3.3/components/antlib/resources/lifecycle.xml:67: impossible to resolve dependencies:
	resolve failed - see output for details

Total time: 37 seconds

Any suggestions why ?
Thank you for your reply.
Best wishes
Roland

**Comment by sbesson** [comment]
Hi @UCLGuichard, we are currently aware of a few unresolved issues with our OMERO 5.3 formula:
- the first one is that the upstream `ice` formula is now shipping Ice 3.7.0 which is not support by OMERO 5.3. Can you give paste the output of `brew info ice` ?
- another known issue is that Homebrew extended some sandboxing rules for tap formulas (see https://github.com/ome/homebrew-alt/pull/136) which probably requires upstream changes.

**Comment by UCLGuichard** [comment]
Hi @sbesson, here is the output:
`ice: stable 3.7.0 (bottled)
Comprehensive RPC framework
https://zeroc.com
/usr/local/Cellar/ice/3.7.0 (1,344 files, 267.3MB) *
  Poured from bottle on 2017-09-05 at 09:27:24
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ice.rb
==> Dependencies
Required: mcpp ✔, lmdb ✔
==> Requirements
Required: macOS >= 10.9 ✔
Optional: java >= 1.8 ✔
==> Options
--with-additional-compilers
	Build additional Slice compilers (slice2py, slice2js, slice2rb)
--with-java
	Build Ice for Java and the IceGrid GUI app
--without-xcode-sdk
	Build without the Xcode SDK for iOS development (includes static libs)`
Hope it helps. I will have a look at the second point.
BW,
Roland

**Comment by jburel** [comment]
To install ice 3.6 you will need to use ``brew install zeroc-ice/tap/ice@3.6``

**Comment by UCLGuichard** [comment]
@jburel still not building

**Comment by jburel** [comment]
you will need to install the Ice extension for Python i.e. ``pip install "zeroc-ice>3.5,<3.7"``

**Comment by hluetck** [comment]
Same problem here. Build fails, even after running all the above steps.

**Comment by jburel** [comment]
We have reviewed our documentation for the coming 5.4.0 (available next week) so it is possible to install OMERO using homebrew without using the formula
see 
https://github.com/openmicroscopy/ome-documentation/pull/1780
and 
https://github.com/openmicroscopy/ome-documentation/pull/1782

**Comment by joshmoore** [comment]
Closing this after substantial changes. If there are issues, please do let us know.
