### ISSUE TITLE
omero failed to build on 10.11.3

### ISSUE THREAD

**Issue by apocryphx** [ome/homebrew-alt#98]
https://gist.github.com/1da11968796e0ca3a9db

omero fails to build on Mac OS X 10.11:

==> Installing omero from ome/alt
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://downloads.openmicroscopy.org/omero/5.2.1/artifacts/openmicroscopy-5.2.1.zip
Already downloaded: /Library/Caches/Homebrew/omero-5.2.1.zip
==> ./build.py -Dice.home=/usr/local/opt/zeroc-ice35 build-default
Last 15 lines from /Users/omero/Library/Logs/Homebrew/omero/01.build.py:
:: ^ see resolution messages for details ^ ::
::::::::::::::::::::::::::::::::::::::::::::::
:: ome#mipav-stubs;5.1.7!mipav-stubs.jar
::::::::::::::::::::::::::::::::::::::::::::::

:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS

BUILD FAILED
/private/tmp/omero20160217-33681-1rnnp2c/openmicroscopy-5.2.1/build.xml:179: The following error occurred while executing this line:
/private/tmp/omero20160217-33681-1rnnp2c/openmicroscopy-5.2.1/components/antlib/resources/global.xml:430: The following error occurred while executing this line:
/private/tmp/omero20160217-33681-1rnnp2c/openmicroscopy-5.2.1/components/antlib/resources/lifecycle.xml:67: impossible to resolve dependencies:
resolve failed - see output for details

Total time: 6 minutes 17 seconds

**Comment by dominikl** [comment]
This looks like a temporary problem with some dependency downloads. Could you try again? I just tried a homebrew omero installation on my Mac (10.11.3), didn't notice a problem.

**Comment by apocryphx** [comment]
Hi Dominik,
Thanks for your fast reply. Sorry I could not solve the problem. I did a complete reinstall: wiped the partition, reinstalled the OS, Xcode, command  line tools, Oracle Java, Homebrew. I followed the steps as outlined on the OMERO web site. I used native Python originally and Homebrew Python in a second attempt .... I always get the same error. Could you give me some pointers as what environment you use? Do you have Apple native Java installed? What other variants should I try? 

Thanks again for all your help.

Best,
Kolja

**Comment by sbesson** [comment]
Hi @apocryphx, sorry to hear you are still having issues with the installation. With the clean partition (I assume the Maven cache under'~/.m2` was also cleared, did the build also fail with a missing `ome#mipav-stubs`? If so, could you list the content of ~/.m2/repository/ome/mipav-stubs/`?

**Comment by apocryphx** [comment]
I repeated the install procedure from scratch. What is new is that the install will now stop (hang). 
Here are the steps:

1.) The partition was completely erased (no residual files whatsoever). 
2.) The latest version of OS X El Capitan was installed
3.) I installed Xcode from the app store. I did "x-code-select -install” to install the command line tools and "sudo xcodebuild - license" to activate the license. 

I then followed the steps as described here:

http://www.openmicroscopy.org/site/support/omero5.2/sysadmins/unix/server-install-homebrew.html <http://www.openmicroscopy.org/site/support/omero5.2/sysadmins/unix/server-install-homebrew.html>

When I get to "brew install omero52 --with-nginx --with-cpp”  the installation (command line process) will hang. I waited 24 hours to make sure it was not waiting for a slow background process. 

I stopped the process with CTRL-C. The folders ~/.m2was and ~/.m2/repository/ome/mipav-stubs/ do not exist. When I run the the same install command again the error message appears:

Last 15 lines from /Users/omero/Library/Logs/Homebrew/omero52/01.build.py:
:: net.sf.ehcache#ehcache-core;2.1.0!ehcache-core.jar
:: backport-util-concurrent#backport-util-concurrent;3.1!backport-util-concurrent.jar
:: quartz#quartz;1.5.2!quartz.jar
::::::::::::::::::::::::::::::::::::::::::::::


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS

BUILD FAILED
/private/tmp/omero5220160226-38476-1nc0plz/openmicroscopy-5.2.1/build.xml:188: The following error occurred while executing this line:
/private/tmp/omero5220160226-38476-1nc0plz/openmicroscopy-5.2.1/components/antlib/resources/global.xml:430: The following error occurred while executing this line:
/private/tmp/omero5220160226-38476-1nc0plz/openmicroscopy-5.2.1/components/antlib/resources/lifecycle.xml:67: impossible to resolve dependencies:
resolve failed - see output for details

T

The folders ~/.m2was and ~/.m2/repository/ome/mipav-stubs/ still do not exist.

I created a new gist under https://gist.github.com/b836192b10caddc12e31 <https://gist.github.com/b836192b10caddc12e31> .

I hope this helps.

Best,
Kolja

**Comment by sbesson** [comment]
Thanks for trying again and sharing the logs.

All your logs point at connection/timeout issues while retrieving the OMERO Java dependencies via Ivy/Maven. We experienced similar failures when our automatic builds were building from clean VMs and caching the dependencies helped solving this problem https://github.com/openmicroscopy/openmicroscopy/blob/develop/.travis.yml#L10.

Could you retry `brew install omero52 --with-nginx --with-cpp` from the current state i.e. without erasing the partition or clearing any cache? I would expect the installation to progress further and more dependencies to be fetched.

**Comment by apocryphx** [comment]
I found out that our corporate web content filter was interfering with the installation / downloads in subtle ways. After I switched to a different network OMERO installed successfully. I consider the problem solved. 

Thank you very much for all your help.

Best,
Kolja

**Comment by sbesson** [comment]
Hi @apocryphx, very glad to hear about it. Closing this issue.
